<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="C:\laragon\www\ci4-books\tests\unit" tests="66" assertions="2" errors="64" warnings="0" failures="0" skipped="0" time="0.390676">
    <testsuite name="Tests\Unit\AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" tests="10" assertions="0" errors="10" warnings="0" failures="0" skipped="0" time="0.078697">
      <testcase name="testIndexReturnsViewWithAuthors" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="31" assertions="0" time="0.030827">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testIndexReturnsViewWithAuthors
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testCreatePostValidData" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="38" assertions="0" time="0.005455">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testCreatePostValidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testCreatePostInvalidData" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="52" assertions="0" time="0.005161">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testCreatePostInvalidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testCreatePostDuplicateName" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="65" assertions="0" time="0.005803">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testCreatePostDuplicateName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditGetValidId" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="81" assertions="0" time="0.005143">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testEditGetValidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditGetInvalidId" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="90" assertions="0" time="0.005372">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testEditGetInvalidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditPostValidData" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="97" assertions="0" time="0.005090">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testEditPostValidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditPostInvalidData" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="113" assertions="0" time="0.005333">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testEditPostInvalidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testDeleteValidId" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="128" assertions="0" time="0.005302">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testDeleteValidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testDeleteInvalidId" class="Tests\Unit\AuthorControllerTest" classname="Tests.Unit.AuthorControllerTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php" line="138" assertions="0" time="0.005210">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorControllerTest::testDeleteInvalidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
    </testsuite>
    <testsuite name="Tests\Unit\AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" tests="9" assertions="0" errors="9" warnings="0" failures="0" skipped="0" time="0.047081">
      <testcase name="testModelCanInsertAuthor" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" line="25" assertions="0" time="0.005121">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelCanInsertAuthor
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanFindAuthor" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" line="37" assertions="0" time="0.005150">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelCanFindAuthor
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanUpdateAuthor" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" line="50" assertions="0" time="0.005094">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelCanUpdateAuthor
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanDeleteAuthor" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" line="68" assertions="0" time="0.005529">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelCanDeleteAuthor
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationFailsWithEmptyName" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" line="81" assertions="0" time="0.005242">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelValidationFailsWithEmptyName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationFailsWithDuplicateName" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" line="94" assertions="0" time="0.005156">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelValidationFailsWithDuplicateName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationFailsWithInvalidCharacters" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" line="108" assertions="0" time="0.005365">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelValidationFailsWithInvalidCharacters
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationPassesWithValidName" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" line="121" assertions="0" time="0.005139">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelValidationPassesWithValidName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanOrderByName" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php" line="131" assertions="0" time="0.005287">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelCanOrderByName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\AuthorModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
    </testsuite>
    <testsuite name="Tests\Unit\BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" tests="12" assertions="0" errors="12" warnings="0" failures="0" skipped="0" time="0.062777">
      <testcase name="testIndexReturnsViewWithBooks" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="33" assertions="0" time="0.005130">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testIndexReturnsViewWithBooks
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testCreatePostValidData" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="40" assertions="0" time="0.005352">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testCreatePostValidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testCreatePostInvalidData" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="63" assertions="0" time="0.005137">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testCreatePostInvalidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testCreatePostWithoutAuthors" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="78" assertions="0" time="0.005325">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testCreatePostWithoutAuthors
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditGetValidId" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="94" assertions="0" time="0.005123">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testEditGetValidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditGetInvalidId" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="107" assertions="0" time="0.005225">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testEditGetInvalidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditPostValidData" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="114" assertions="0" time="0.005156">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testEditPostValidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditPostInvalidData" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="142" assertions="0" time="0.005243">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testEditPostInvalidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testDeleteValidId" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="163" assertions="0" time="0.005196">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testDeleteValidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testDeleteInvalidId" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="177" assertions="0" time="0.005406">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testDeleteInvalidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testGetBookValidId" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="185" assertions="0" time="0.005328">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testGetBookValidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testGetBookInvalidId" class="Tests\Unit\BookControllerTest" classname="Tests.Unit.BookControllerTest" file="C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php" line="199" assertions="0" time="0.005156">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookControllerTest::testGetBookInvalidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookControllerTest.php:26
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
    </testsuite>
    <testsuite name="Tests\Unit\BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" tests="11" assertions="0" errors="11" warnings="0" failures="0" skipped="0" time="0.058992">
      <testcase name="testModelCanInsertBook" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="29" assertions="0" time="0.005229">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testModelCanInsertBook
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanFindBook" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="44" assertions="0" time="0.005111">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testModelCanFindBook
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanUpdateBook" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="60" assertions="0" time="0.005188">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testModelCanUpdateBook
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanDeleteBook" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="81" assertions="0" time="0.005695">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testModelCanDeleteBook
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationFailsWithEmptyTitle" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="97" assertions="0" time="0.005311">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testModelValidationFailsWithEmptyTitle
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationFailsWithInvalidValue" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="112" assertions="0" time="0.005198">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testModelValidationFailsWithInvalidValue
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationFailsWithInvalidPublicationDate" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="127" assertions="0" time="0.005240">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testModelValidationFailsWithInvalidPublicationDate
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationPassesWithValidData" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="143" assertions="0" time="0.005152">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testModelValidationPassesWithValidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testGetBooksWithRelations" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="156" assertions="0" time="0.005228">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testGetBooksWithRelations
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testGetBookWithRelations" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="179" assertions="0" time="0.006249">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testGetBookWithRelations
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testGetBookWithRelationsReturnsNullForNonExistentBook" class="Tests\Unit\BookModelTest" classname="Tests.Unit.BookModelTest" file="C:\laragon\www\ci4-books\tests\unit\BookModelTest.php" line="204" assertions="0" time="0.005391">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\BookModelTest::testGetBookWithRelationsReturnsNullForNonExistentBook
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\BookModelTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
    </testsuite>
    <testsuite name="HealthTest" file="C:\laragon\www\ci4-books\tests\unit\HealthTest.php" tests="2" assertions="2" errors="0" warnings="0" failures="0" skipped="0" time="0.013749">
      <testcase name="testIsDefinedAppPath" class="HealthTest" classname="HealthTest" file="C:\laragon\www\ci4-books\tests\unit\HealthTest.php" line="13" assertions="1" time="0.003452"/>
      <testcase name="testBaseUrlHasBeenSet" class="HealthTest" classname="HealthTest" file="C:\laragon\www\ci4-books\tests\unit\HealthTest.php" line="18" assertions="1" time="0.010297"/>
    </testsuite>
    <testsuite name="Tests\Unit\ReportControllerTest" file="C:\laragon\www\ci4-books\tests\unit\ReportControllerTest.php" tests="3" assertions="0" errors="3" warnings="0" failures="0" skipped="0" time="0.016051">
      <testcase name="testIndexReturnsViewWithReportData" class="Tests\Unit\ReportControllerTest" classname="Tests.Unit.ReportControllerTest" file="C:\laragon\www\ci4-books\tests\unit\ReportControllerTest.php" line="27" assertions="0" time="0.005462">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\ReportControllerTest::testIndexReturnsViewWithReportData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\ReportControllerTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testGetConsolidatedReportReturnsArray" class="Tests\Unit\ReportControllerTest" classname="Tests.Unit.ReportControllerTest" file="C:\laragon\www\ci4-books\tests\unit\ReportControllerTest.php" line="34" assertions="0" time="0.005242">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\ReportControllerTest::testGetConsolidatedReportReturnsArray
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\ReportControllerTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testGetConsolidatedReportStructure" class="Tests\Unit\ReportControllerTest" classname="Tests.Unit.ReportControllerTest" file="C:\laragon\www\ci4-books\tests\unit\ReportControllerTest.php" line="41" assertions="0" time="0.005347">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\ReportControllerTest::testGetConsolidatedReportStructure
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\ReportControllerTest.php:23
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
    </testsuite>
    <testsuite name="Tests\Unit\SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" tests="10" assertions="0" errors="10" warnings="0" failures="0" skipped="0" time="0.063141">
      <testcase name="testIndexReturnsViewWithSubjects" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="29" assertions="0" time="0.005294">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testIndexReturnsViewWithSubjects
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testCreatePostValidData" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="36" assertions="0" time="0.005406">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testCreatePostValidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testCreatePostInvalidData" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="50" assertions="0" time="0.010197">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testCreatePostInvalidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testCreatePostDuplicateName" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="63" assertions="0" time="0.007117">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testCreatePostDuplicateName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditGetValidId" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="79" assertions="0" time="0.006963">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testEditGetValidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditGetInvalidId" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="88" assertions="0" time="0.005737">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testEditGetInvalidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditPostValidData" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="95" assertions="0" time="0.005410">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testEditPostValidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testEditPostInvalidData" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="111" assertions="0" time="0.005668">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testEditPostInvalidData
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testDeleteValidId" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="126" assertions="0" time="0.005450">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testDeleteValidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testDeleteInvalidId" class="Tests\Unit\SubjectControllerTest" classname="Tests.Unit.SubjectControllerTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php" line="136" assertions="0" time="0.005899">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectControllerTest::testDeleteInvalidId
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectControllerTest.php:24
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
    </testsuite>
    <testsuite name="Tests\Unit\SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" tests="9" assertions="0" errors="9" warnings="0" failures="0" skipped="0" time="0.050189">
      <testcase name="testModelCanInsertSubject" class="Tests\Unit\SubjectModelTest" classname="Tests.Unit.SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" line="25" assertions="0" time="0.005403">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectModelTest::testModelCanInsertSubject
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanFindSubject" class="Tests\Unit\SubjectModelTest" classname="Tests.Unit.SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" line="37" assertions="0" time="0.005758">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectModelTest::testModelCanFindSubject
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanUpdateSubject" class="Tests\Unit\SubjectModelTest" classname="Tests.Unit.SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" line="50" assertions="0" time="0.005449">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectModelTest::testModelCanUpdateSubject
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanDeleteSubject" class="Tests\Unit\SubjectModelTest" classname="Tests.Unit.SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" line="68" assertions="0" time="0.005640">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectModelTest::testModelCanDeleteSubject
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationFailsWithEmptyName" class="Tests\Unit\SubjectModelTest" classname="Tests.Unit.SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" line="81" assertions="0" time="0.005959">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectModelTest::testModelValidationFailsWithEmptyName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationFailsWithDuplicateName" class="Tests\Unit\SubjectModelTest" classname="Tests.Unit.SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" line="94" assertions="0" time="0.006031">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectModelTest::testModelValidationFailsWithDuplicateName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationFailsWithInvalidCharacters" class="Tests\Unit\SubjectModelTest" classname="Tests.Unit.SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" line="108" assertions="0" time="0.005423">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectModelTest::testModelValidationFailsWithInvalidCharacters
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelValidationPassesWithValidName" class="Tests\Unit\SubjectModelTest" classname="Tests.Unit.SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" line="121" assertions="0" time="0.005315">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectModelTest::testModelValidationPassesWithValidName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
      <testcase name="testModelCanOrderByName" class="Tests\Unit\SubjectModelTest" classname="Tests.Unit.SubjectModelTest" file="C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php" line="131" assertions="0" time="0.005211">
        <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\SubjectModelTest::testModelCanOrderByName
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:428
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:59
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:80
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:56
C:\laragon\www\ci4-books\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:249
C:\laragon\www\ci4-books\tests\unit\SubjectModelTest.php:21
phpvfscomposer://C:\laragon\www\ci4-books\vendor\phpunit\phpunit\phpunit:106</error>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
